# Generated by Django 4.2.7 on 2023-12-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='playlist_id',
        ),
    ]
